name: create_custom_wvd_image

on: push

jobs:
  BUILD-CUSTOM-IMAGE:
    runs-on: ubuntu-latest    
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
  

    - name: AZURE LOGIN 
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: BUILD WEBAPP
      run: sudo ${{ GITHUB.WORKSPACE }}/webApp/buildscript.sh # Runs necessary build scripts and copies built artifacts to  ${{ GITHUB.WORKSPACE }}/workflow_artifacts
      
    - name: Build Azure Virtual Machine Image
      uses: Azure/build-vm-image@v0
      with:
       resource-group-name: 'RG-GitHub-AIB'
       managed-identity: 'AIBIdentity'
       location: 'eastus'
       source-os-type: 'windows'        
       source-image: MicrosoftWindowsDesktop:Windows-10:20h1-evd        
       customizer-script: |
          & 'c:\workflow-artifacts\webApp\webconfig.ps1'
