name: create_custom_wvd_image

on: push

jobs:
  BUILD-CUSTOM-IMAGE:
    runs-on: ubuntu-latest    
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
  

    - name: AZURE LOGIN 
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_SP}}

   # - name: BUILD WEBAPP
    #  run: sudo ${{ GITHUB.WORKSPACE }}/webApp/buildscript.sh # Runs necessary build scripts and copies built artifacts to  ${{ GITHUB.WORKSPACE }}/workflow_artifacts
      
    - name: Build Azure Virtual Machine Image
      uses: Azure/build-vm-image@v0
      with:
       resource-group-name: 'RG-GitHub-AIB'
       managed-identity: 'AIBIdentity'
       location: 'eastus'
       source-os-type: 'windows'
       source-image-type: 'platformImage'   
       source-image: MicrosoftWindowsDesktop:Windows-10:20h1-evd:latest        
   #    customizer-script: |
   #       & 'c:\workflow-artifacts\webApp\webconfig.ps1'
     
       dist-type: 'SharedImageGallery'
       dist-resource-id: '/subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/RG-WVD-SIG/providers/Microsoft.Compute/galleries/GithubSharedImages/images/GitHubAIB/versions/0.1.${{ GITHUB.RUN_ID }}' #Replace with the resource id of your shared image  gallery's image definition
       dist-location: 'eastus'
